# Generated by Django 4.0.6 on 2022-11-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexCodeTask', '0004_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='url',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='gets_original',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='gets_link',
            field=models.BooleanField(null=True),
        ),
    ]
