# Generated by Django 4.0.6 on 2022-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexCodeTask', '0006_tier_expiring_link_binaryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='binaryphoto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
