# Generated by Django 4.0.6 on 2022-11-14 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexCodeTask', '0008_binaryphoto_path_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binaryphoto',
            name='expires',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='binaryphoto',
            name='url',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
