# Generated by Django 4.0.6 on 2022-11-15 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexCodeTask', '0009_alter_binaryphoto_expires_alter_binaryphoto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='gets_link',
        ),
        migrations.AlterField(
            model_name='binaryphoto',
            name='expires',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
